config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    root "static_pages#home"
    get "/news",    to: "static_pages#news"
    get "/contact", to: "static_pages#contact"
    get "/genres",  to: "static_pages#genres"
    post "/rate",   to: "rater#create"

    resources :posts do
      resources :comments
    end
    resources :users, only: [:show, :index] do
      member do
        get :following, :followers, :friends
      end
    end
    resources :search, only: [:index]
    resources :categories, only: [:index, :show]
    resources :relationships, only: [:create, :accept, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit, :update]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @comment.destroy
      respond_to do |format|
        format.js
      end
    else
      redirect_to @comment.post
    end
  end

  def edit
  end

  def update
    @comment.update comment_params
    respond_to do |format|
      format.js
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = t("you_can_not_do_that")
      redirect_to @post
    end
  end

  def comment_params
    params[:comment].permit(:content)
  end
end

app/views/comments/_comment.html.erb
<li id="comment-content-<%= comment.id %>" class="dialogbox">
  <div class="body">
    <span class="tip tip-right"></span>
    <div class="message">
      <p><b><%= comment.user.name %></b></p>
      <p id="comment-text-<%= comment.id %>"><%= comment.content %></p>

      <% if current_user == comment.user %>
        <%= time_ago_in_words comment.created_at %><%= t(".ago")%>
        <%= link_to t(".delete_comment"), [comment.post, comment], remote: true, method: :delete %> /
        <%= link_to t(".edit_comment"), edit_post_comment_path(comment.post,comment), remote: true %>
      <% end %>
    </div>
  </div>
</li>

app/views/comments/_edit.html.erb
<%= form_for [@post, @comment], remote: true do |f| %>
  <%= f.text_area :content, class: "comments-form-edit" %>
  <%= f.submit "Update more more more", class: "update-comment-btn" %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build], remote: true do |f| %>
  <p><%= f.text_area :content, class: "comments-form" %></p>
  <p><%= f.submit class: "comment-button", value: t(".send") %></p>
<% end %>

app/views/comments/_list_comment.html.erb
<ul id="comment-list">
  <%= render @comments %>
</ul>

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $('#comment-list').prepend('<%= escape_javascript render @comment %>');
  $('#comment_content').val('');
<% else %>
  alert('<%= escape_javascript I18n.t("comments.create.not_empty") %>');
<% end %>

app/views/comments/destroy.js.erb
$("#comment-content-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-content-<%= @comment.id %>").html("<%= escape_javascript render('comments/edit') %>");

app/views/comments/update.js.erb
$("#comment-content-<%= @comment.id %>").html("<%= j render('comments/comment', comment: @comment) %>")