config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    root "static_pages#home"
    get "/news",    to: "static_pages#news"
    get "/contact", to: "static_pages#contact"
    get "/genres",  to: "static_pages#genres"
    post "/rate",   to: "rater#create"

    resources :posts do
      resources :comments
    end
    resources :users, only: [:show, :index] do
      member do
        get :following, :followers, :friends
      end
    end
    resources :search, only: [:index]
    resources :categories, only: [:index, :show]
    resources :relationships, only: [:create, :accept, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :trackable, :confirmable
  devise :database_authenticatable, :registerable, :recoverable, :confirmable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts
  has_many :comments

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  ratyrate_rater

  def friends
    (following + followers).uniq
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: :index

  def show
    @posts = @user.posts.load_info_new.order("created_at DESC").paginate page: params[:page], per_page: 10
  end

  def index
    @users = User.all
  end

  def following
    @title = "Following"
    @users = @user.following.paginate page: params[:page]
    render 'show_friends'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate page: params[:page]
    render 'show_friends'
  end

  def friends
    @title = "Friends"
    @users = @user.friends.paginate page: params[:page]
    render 'show_friends'
  end

  private

  def load_user
    @user  = User.find_by id: params[:id]
    redirect_to users_path unless @user
  end
end

app/views/users/_addfriend.html.erb
<%= form_for(current_user.active_relationships.build, remote: true ) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Add Friend", class: "btn btn-primary" %>
<% end %>

app/views/users/_addfriend_form.html.erb
<div id="follow-form-<%= user.id %>">
  <% if current_user.following?(user) %>
    <%= render 'unfriend', user: user %>
  <% else %>
    <%= render 'addfriend', user: user %>
  <% end %>
</div>

app/views/users/_unfriend.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete },
             remote: true do |f| %>
  <%= f.submit "Unfriend", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user != user %>
    <%= render "users/addfriend_form", user: user %>
  <% end %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

<section class="stats">
  <%= render 'shared/stats' %>
</section>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

  <h1><%= t(".name")%>: <%= @user.name %></h1>
  <div>
  <% if current_user != @user %>
    <%= render 'users/addfriend_form', user: @user %>
  <% else %>
   <%= link_to t(".edit_profile"), edit_user_registration_path %></br>
   <%= link_to t(".friends"), friends_user_path %>
  <% end %>
  </div>
<div class="row-info-post-user">
  <h1><%= t(".your_posts") %></h1>
  <div id="myTabContent" class="col-md-8 tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="home1" aria-labelledby="home1-tab">
      <div class="wthree-news-top-left">
        <% if @posts.present? %>
          <% @posts.each do |post| %>
            <div class="col-md-6 w3-agileits-news-left">
              <div class="col-sm-5 wthree-news-img">
                <%= link_to post_path(post) do %>
                  <%= image_tag(post.image, class: "image-post-news") %>
                <% end %>
              </div>
              <div class="col-sm-7 wthree-news-info">
                <h5><%= link_to post.title, post_path(post) %></h5>
                <p>Người đăng: <%= post.user.name %></p>
                <p><%= truncate(post.content, length: 80) %></p>
                <ul>
                  <li><i class="fa fa-clock-o" aria-hidden="true"></i><%= post.year %></li>
                  <li><i class="fa fa-eye" aria-hidden="true"></i><%= post.view %></li>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <p><%= will_paginate @posts, class: "will-paginate-show" %></p>
    </div>
  </div>
</div>

app/views/users/show_friends.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-8">
    <h3><%= @title %>: <%= @user.friends.count %> </h3>
    <% if @users.any? %>
      <ul class="users-follow">
       <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>