config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    root "static_pages#home"
    get "/news",    to: "static_pages#news"
    get "/contact", to: "static_pages#contact"
    get "/genres",  to: "static_pages#genres"
    post "/rate",   to: "rater#create"

    resources :posts do
      resources :comments
    end
    resources :users, only: [:show, :index] do
      member do
        get :following, :followers, :friends
      end
    end
    resources :search, only: [:index]
    resources :categories, only: [:index, :show]
    resources :relationships, only: [:create, :accept, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="col-md-5 w3ls_footer_grid1_left">
      <p>&copy;<%= t(".caption") %><a href="https://awesome-academy.com/">AWESOME ACADEMY</a></p>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- header -->
  <div class="header">
    <div class="container">
      <div class="w3layouts_logo">
        <a href="/"><h1>One<span>Movies</span></h1></a>
      </div>
      <div class="w3_search">
        <%= search_form_for @q, url: search_index_path do |f| %>
          <%= f.text_field :title_or_original_name_cont, placeholder: t(".search") %>
          <%= f.submit value: t(".go") %>
        <% end %>
      </div>
      <div class="w3l_sign_in_register">
        <ul>
          <%= form_tag '/', :class => 'locale', :method => :get do %>
            <%= select_tag 'locale',
              options_for_select(LANGUAGES, I18n.locale.to_s),
              :onchange => 'this.form.submit()' %>
          <% end %>
          <% if user_signed_in? %>
            <li><%= link_to t(".profile"), user_path(current_user) %></li>
            <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to t(".register"), new_user_registration_path %></li>
            <li><%= link_to t(".login"), new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
<!-- //header -->
<!-- nav -->
  <div class="movies_nav">
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="navbar-header navbar-left">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only"><%= t(".toggle_navigation") %></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
          <nav>
            <ul class="nav navbar-nav">
              <li><%= link_to t(".home"), root_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".genres") %><b class="caret"></b></a>
                <ul class="dropdown-menu multi-column columns-3">
                  <div class="row">
                    <% all_categories.each do |group_category| %>
                      <div class="col-sm-4">
                        <ul class="multi-column-dropdown">
                          <% group_category.compact.each do |category| %>
                            <ul class="nav nav-pills nav-stacked">
                              <li class="<%= 'active' if category == @category %>">
                              <%= link_to category.name, category %>
                              </li>
                            </ul><br>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                  </div>
                  <div class="clearfix"></div>
                </ul>
              </li>
              <li><%= link_to t(".contact"), contact_path%></li>
              <li><%= link_to t(".news"), news_path %></li>
              <li>
                <% if user_signed_in? %>
                  <%= link_to t(".all_users"), users_path %>
                <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </nav>
    </div>
  </div>
<!-- //nav -->

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li class="errors_message" >
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_template_assets.html.erb
<!-- banner-slider -->
<link href="css/jquery.slidey.min.css" rel="stylesheet">
<!-- //banner-slider -->
<!-- pop-up -->
<link href="css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
<!-- //pop-up -->
<!-- font-awesome icons -->
<link rel="stylesheet" href="css/font-awesome.min.css" />
<!-- //font-awesome icons -->
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<!-- //js -->
<!-- banner-bottom-plugin -->
<link href="css/owl.carousel.css" rel="stylesheet" type="text/css" media="all">
<script src="js/owl.carousel.js"></script>
<script>
  $(document).ready(function() {
    $("#owl-demo").owlCarousel({

      autoPlay: 3000, //Set AutoPlay to 3 seconds

      items : 5,
      itemsDesktop : [640,4],
      itemsDesktopSmall : [414,3]

    });

  });
</script>
<!-- //banner-bottom-plugin -->
<link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="js/move-top.js"></script>
<script type="text/javascript" src="js/easing.js"></script>
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $(".scroll").click(function(event){
      event.preventDefault();
      $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
    });
  });
</script>

<!-- //general -->
  <!-- pop-up-box -->
    <script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
  <!--//pop-up-box -->
  <div id="small-dialog" class="mfp-hide">
    <iframe src="https://player.vimeo.com/video/164819130?title=0&byline=0"></iframe>
  </div>
  <div id="small-dialog1" class="mfp-hide">
    <iframe src="https://player.vimeo.com/video/148284736"></iframe>
  </div>
  <div id="small-dialog2" class="mfp-hide">
    <iframe src="https://player.vimeo.com/video/165197924?color=ffffff&title=0&byline=0&portrait=0"></iframe>
  </div>
  <script>
    $(document).ready(function() {
    $('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
      type: 'inline',
      fixedContentPos: false,
      fixedBgPos: true,
      overflowY: 'auto',
      closeBtnInside: true,
      preloader: false,
      midClick: true,
      removalDelay: 300,
      mainClass: 'my-mfp-zoom-in'
    });

    });
  </script>
<!-- //Latest-tv-series -->
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>
<script>
$(document).ready(function(){
    $(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');
        }
    );
});
</script>
<!-- //Bootstrap Core JavaScript -->
<!-- here stars scrolling icon -->
  <script type="text/javascript">
    $(document).ready(function() {
      /*
        var defaults = {
        containerID: 'toTop', // fading element id
        containerHoverID: 'toTopHover', // fading element hover id
        scrollSpeed: 1200,
        easingType: 'linear'
        };
      */

      $().UItoTop({ easingType: 'easeOutQuart' });

      });
  </script>
<!-- //here ends scrolling icon -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= render "layouts/template_assets" %>
  </body>
</html>